/**
 * AGENTS.md Auto-Generator
 *
 * Generates project-specific AI agent instructions based on the knowledge graph.
 * Outputs to `AGENTS.md` (or `.recon/AGENTS.md`) during `recon index`.
 *
 * The generated file helps AI coding agents understand:
 * - Project architecture (packages, key modules)
 * - Must-check rules (critical shared symbols)
 * - Execution flows overview
 * - Recommended workflows
 */

import type { KnowledgeGraph } from '../graph/graph.js';
import { detectProcesses } from '../graph/process.js';

// ─── Types ──────────────────────────────────────────────────────

interface PackageSummary {
    name: string;
    nodeCount: number;
    exportedCount: number;
    languages: Set<string>;
}

interface CriticalSymbol {
    name: string;
    type: string;
    file: string;
    callerCount: number;
}

// ─── Generator ──────────────────────────────────────────────────

export function generateAgentsMd(
    graph: KnowledgeGraph,
    repoName?: string,
): string {
    const lines: string[] = [];
    const projectName = repoName || 'this project';

    // ─── Header
    lines.push(`# AGENTS.md — ${projectName}`);
    lines.push('');
    lines.push('> Auto-generated by [Recon](https://github.com/jhm1909/recon). Do not edit manually.');
    lines.push('> Regenerate with: `npx recon-mcp index`');
    lines.push('');

    // ─── Stats overview
    const nodeCount = graph.nodeCount;
    const relCount = graph.relationshipCount;
    const languages = new Set<string>();
    for (const node of graph.nodes.values()) {
        if (node.language) languages.add(node.language);
    }

    lines.push('## Project Overview');
    lines.push('');
    lines.push(`- **Symbols:** ${nodeCount}`);
    lines.push(`- **Relationships:** ${relCount}`);
    lines.push(`- **Languages:** ${[...languages].join(', ') || 'unknown'}`);
    lines.push('');

    // ─── Package Architecture
    const packages = getPackageSummaries(graph);
    if (packages.length > 0) {
        lines.push('## Architecture');
        lines.push('');
        lines.push('| Package | Symbols | Exported | Languages |');
        lines.push('|---------|---------|----------|-----------|');
        for (const pkg of packages.slice(0, 15)) {
            lines.push(`| \`${pkg.name}\` | ${pkg.nodeCount} | ${pkg.exportedCount} | ${[...pkg.languages].join(', ')} |`);
        }
        lines.push('');
    }

    // ─── Critical Shared Symbols
    const critical = findCriticalSymbols(graph);
    if (critical.length > 0) {
        lines.push('## ⚠️ Critical Shared Symbols');
        lines.push('');
        lines.push('These symbols have **many callers**. Changes to them have high blast radius.');
        lines.push('**Always run `recon_impact` before modifying these.**');
        lines.push('');
        lines.push('| Symbol | Type | File | Callers |');
        lines.push('|--------|------|------|---------|');
        for (const sym of critical) {
            lines.push(`| \`${sym.name}\` | ${sym.type} | \`${sym.file}\` | ${sym.callerCount} |`);
        }
        lines.push('');
    }

    // ─── Execution Flows
    const processes = detectProcesses(graph, { limit: 10 });
    if (processes.length > 0) {
        lines.push('## Execution Flows');
        lines.push('');
        lines.push('Key execution paths through the codebase:');
        lines.push('');
        for (const p of processes.slice(0, 5)) {
            const tag = p.processType === 'cross_community' ? '🔀' : '📦';
            lines.push(`- ${tag} **${p.label}** — ${p.steps.length} steps, depth ${p.depth}`);
        }
        lines.push('');
        lines.push('Use `recon_processes` for full traces with call chains.');
        lines.push('');
    }

    // ─── Rules for AI Agents
    lines.push('## Rules for AI Agents');
    lines.push('');
    lines.push('### Always Do');
    lines.push('');
    lines.push('1. **Before modifying exported functions/types:**');
    lines.push('   ```');
    lines.push('   recon_impact({target: "<name>", direction: "upstream"})');
    lines.push('   ```');
    lines.push('   Review d=1 (WILL BREAK) items. If risk is HIGH/CRITICAL, warn user.');
    lines.push('');
    lines.push('2. **Before committing:**');
    lines.push('   ```');
    lines.push('   recon_detect_changes()');
    lines.push('   ```');
    lines.push('   Check blast radius of staged changes.');
    lines.push('');
    lines.push('3. **When exploring unfamiliar code:**');
    lines.push('   ```');
    lines.push('   recon_packages()          → architecture overview');
    lines.push('   recon_query({query: "X"}) → find symbols');
    lines.push('   recon_context({name: "X"})→ callers, callees, imports');
    lines.push('   ```');
    lines.push('');

    lines.push('### When Debugging');
    lines.push('');
    lines.push('1. `recon_context({name: "<broken_function>"})` → see all callers and callees');
    lines.push('2. `recon_processes` → trace execution flow to find where data flows');
    lines.push('3. `recon_impact({target: "<suspect>", direction: "downstream"})` → what does it affect?');
    lines.push('');

    lines.push('### When Refactoring');
    lines.push('');
    lines.push('1. `recon_impact` on target → understand blast radius');
    lines.push('2. `recon_rename({symbol_name: "old", new_name: "new", dry_run: true})` → preview');
    lines.push('3. Apply rename with `dry_run: false`');
    lines.push('4. `recon_detect_changes()` → verify');
    lines.push('');

    lines.push('### Never Do');
    lines.push('');
    lines.push('- ❌ Modify critical shared symbols without running `recon_impact` first');
    lines.push('- ❌ Rename exported symbols with find-and-replace (use `recon_rename` instead)');
    lines.push('- ❌ Assume a function is unused without checking `recon_context`');
    lines.push('');

    return lines.join('\n');
}

// ─── Helpers ────────────────────────────────────────────────────

function getPackageSummaries(graph: KnowledgeGraph): PackageSummary[] {
    const pkgMap = new Map<string, PackageSummary>();

    for (const node of graph.nodes.values()) {
        if (!node.package) continue;
        let pkg = pkgMap.get(node.package);
        if (!pkg) {
            pkg = { name: node.package, nodeCount: 0, exportedCount: 0, languages: new Set() };
            pkgMap.set(node.package, pkg);
        }
        pkg.nodeCount++;
        if (node.exported) pkg.exportedCount++;
        if (node.language) pkg.languages.add(node.language);
    }

    return Array.from(pkgMap.values())
        .sort((a, b) => b.nodeCount - a.nodeCount);
}

function findCriticalSymbols(graph: KnowledgeGraph): CriticalSymbol[] {
    const callerCounts = new Map<string, number>();

    for (const rel of graph.allRelationships()) {
        if (rel.type === 'CALLS' || rel.type === 'CALLS_API') {
            callerCounts.set(rel.targetId, (callerCounts.get(rel.targetId) || 0) + 1);
        }
    }

    const critical: CriticalSymbol[] = [];
    for (const [nodeId, count] of callerCounts) {
        if (count < 3) continue; // Only symbols called by 3+ callers
        const node = graph.getNode(nodeId);
        if (!node || !node.exported) continue;

        critical.push({
            name: node.name,
            type: node.type,
            file: node.file,
            callerCount: count,
        });
    }

    return critical.sort((a, b) => b.callerCount - a.callerCount).slice(0, 10);
}
